[wokwi]
version = 1
firmware = "build/effects.ino.hex"
elf = "build/effects.ino.elf"

[[part]]
type = "wokwi-arduino-nano"
id = "nano"

[[part]]
type = "wokwi-neopixel-canvas"
id = "strip1"
attrs = { pin = "6", rows = "1", cols = "25" }

[[connection]]
from = "strip1:DIN"
to = "nano:6"

[[connection]]
from = "strip1:GND"
to = "nano:GND.1"

[[connection]]
from = "strip1:VCC"
to = "nano:5V"
